#!/bin/sh
#
#    00-header - create the header of the MOTD
#    Copyright (C) 2009-2010 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

B='\033[0;34m'
N='\033[0m' # 没有颜色
echo "\033[0;34m
                    0110											
                   01  010  00000                                 
                   11    000000011                                
                 0010          01                                 
        00100001100           01                                  
       010  010              0010                                 
       0100011  00000          010              000               
         0000  010 01     00000001             010010             
              010  010  01000                 010  010            
             010    01010        000         01     010           
            11        0        0100010     010        11          
          010                  10   10    010          010        
         010                   001111    010            010       
        010                         10  010              010      
       010    0000000                0111      11111      010     
      11     00     00                           111        11    
    010      00     00                           111         010  
   010       00     00                           111          010 
  010        00     00                           111           010
  01         00     00                           111            10
  11          0000000                          1111111          11
  11                               0110                         11
  01                        010   00  00   00                   10
  010                 010  00 00  00  00  0000                 010
   010          010  01 10 00 00  00  00 00  00 00  010       010 
     0100      00 00 01 10 00 00  00  00 00  00 00 00 10    0010  
       0001000000 00 01 10 00  00000  00 00  00 00 00 01000100    
                   000  10 00         00 00   010                 
                        10 00         00 00                       
                         010           010                        
  					                                            
    11         0001   10000001   10000    00000   10000001          
    00       101  10     00     00   11  00   01     00             
    00       01          00      010     000000      00             
    00       01          00        101   00          00             
    00       101  10     00     11   01  00          00             
    1000001    1001      11      00001   00       10000001          
\033[0m"

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

printf "Welcome to %s (%s %s %s)\n" "$DISTRIB_DESCRIPTION" "$(uname -o)" "$(uname -r)" "$(uname -m)"
